"""Curated seed list of large Greek companies + multinationals operating in Greece.

Each entry is pre-vetted to meet at least one criterion, so the classifier only
has to write the tailored ALTER EGO pitch (fast + reliable for a local model).

Criteria tags:
  - "brand_name"          recognizable national/multinational brand
  - "large_footprint"     big physical facilities (offices/stores/warehouses/etc.)
  - "large_greek_company" major Greek company / group / ATHEX-listed

`domain` is used by the email finder. `note` is a footprint/why hint.
"""

SEED_COMPANIES = [
    # ── Large Greek corporates / groups (ATHEX heavyweights) ──────────────────
    {"name": "ΔΕΗ (Public Power Corporation)", "domain": "dei.gr", "sector": "Energy / Utilities",
     "criteria": ["large_greek_company", "large_footprint"], "note": "National power utility; vast estate of offices, plants, substations nationwide."},
    {"name": "OTE Group (Cosmote)", "domain": "cosmote.gr", "sector": "Telecom",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "Largest Greek telecom; HQ campus + stores + data/network sites."},
    {"name": "HELLENiQ ENERGY (Hellenic Petroleum)", "domain": "helleniqenergy.gr", "sector": "Energy / Refining",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Refineries, depots, HQ — high-security industrial footprint."},
    {"name": "Motor Oil Hellas", "domain": "moh.gr", "sector": "Energy / Refining",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Corinth refinery complex + offices."},
    {"name": "Metlen Energy & Metals (Mytilineos)", "domain": "metlengroup.com", "sector": "Industry / Energy",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Metallurgy plants + energy assets; large industrial sites."},
    {"name": "OPAP", "domain": "opap.gr", "sector": "Gaming / Entertainment",
     "criteria": ["large_greek_company", "brand_name"], "note": "HQ + nationwide retail agency network."},
    {"name": "Titan Cement", "domain": "titan-cement.com", "sector": "Building materials",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Cement plants + quarries + offices."},
    {"name": "Coca-Cola HBC", "domain": "coca-colahellenic.com", "sector": "Beverages",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "Bottling plants + distribution; huge footprint."},
    {"name": "Jumbo", "domain": "jumbo.gr", "sector": "Retail",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "Big-box stores + large logistics warehouses."},
    {"name": "Public Power - Sklavenitis", "domain": "sklavenitis.gr", "sector": "Retail / Supermarkets",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Largest Greek supermarket chain + distribution centers."},
    {"name": "Alpha Bank", "domain": "alpha.gr", "sector": "Banking",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "HQ + nationwide branch network."},
    {"name": "Eurobank", "domain": "eurobank.gr", "sector": "Banking",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "HQ + branches."},
    {"name": "National Bank of Greece", "domain": "nbg.gr", "sector": "Banking",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "Largest Greek bank; large HQ + branches."},
    {"name": "Piraeus Bank", "domain": "piraeusbank.gr", "sector": "Banking",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "HQ + branch network."},
    {"name": "Aegean Airlines", "domain": "aegeanair.com", "sector": "Aviation",
     "criteria": ["large_greek_company", "brand_name", "large_footprint"], "note": "HQ, hangars, airport offices, lounges."},
    {"name": "GEK Terna", "domain": "gekterna.com", "sector": "Construction / Infrastructure",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Concessions, HQ, large project sites."},
    {"name": "ELLAKTOR", "domain": "ellaktor.com", "sector": "Construction / Infrastructure",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Construction + concessions + facilities."},
    {"name": "Lamda Development", "domain": "lamdadev.com", "sector": "Real Estate",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Ellinikon mega-project + malls (The Mall, Golden Hall, Mediterranean Cosmos)."},
    {"name": "Fourlis Group", "domain": "fourlis.gr", "sector": "Retail",
     "criteria": ["large_greek_company", "large_footprint"], "note": "IKEA + Intersport + Holland & Barrett franchises; big stores + logistics."},
    {"name": "Sarantis Group", "domain": "sarantisgroup.com", "sector": "Consumer goods",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Factories + distribution across SE Europe."},
    {"name": "Viohalco / ElvalHalcor", "domain": "elvalhalcor.com", "sector": "Metals / Industry",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Aluminium/copper plants — large industrial estate."},
    {"name": "Intralot", "domain": "intralot.com", "sector": "Gaming tech",
     "criteria": ["large_greek_company", "brand_name"], "note": "HQ + tech/data operations."},
    {"name": "PPC Renewables / Terna Energy", "domain": "terna-energy.com", "sector": "Renewables",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Wind/solar parks + offices."},
    {"name": "Plaisio Computers", "domain": "plaisio.gr", "sector": "Retail / Electronics",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Stores + large logistics center."},
    {"name": "Kotsovolos (Public)", "domain": "public.gr", "sector": "Retail / Electronics",
     "criteria": ["brand_name", "large_footprint"], "note": "Electronics retail chain + warehouses."},
    {"name": "Vivartia / Delta Foods", "domain": "vivartia.com", "sector": "Food production",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Dairy/food plants — high-hygiene production."},
    {"name": "Chipita", "domain": "chipita.com", "sector": "Food production",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Bakery/snack factories."},
    {"name": "Frigoglass", "domain": "frigoglass.com", "sector": "Industry",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Cooler manufacturing plants."},
    {"name": "AB Vassilopoulos", "domain": "ab.gr", "sector": "Retail / Supermarkets",
     "criteria": ["large_footprint", "brand_name"], "note": "Supermarket chain (Ahold Delhaize) + DCs."},
    {"name": "Masoutis", "domain": "masoutis.gr", "sector": "Retail / Supermarkets",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Northern Greece supermarket leader + logistics."},
    {"name": "Lidl Hellas", "domain": "lidl-hellas.gr", "sector": "Retail / Supermarkets",
     "criteria": ["brand_name", "large_footprint"], "note": "Discount chain + big regional warehouses."},
    {"name": "Hellenic Train (OSE)", "domain": "hellenictrain.gr", "sector": "Transport",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Stations, depots, offices nationwide."},
    {"name": "Athens International Airport", "domain": "aia.gr", "sector": "Aviation / Infrastructure",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Massive terminal + airside facilities, high footfall."},
    {"name": "Piraeus Port Authority (OLP/COSCO)", "domain": "olp.gr", "sector": "Ports / Logistics",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Port terminals, warehouses, offices."},
    {"name": "PPC / ΔΕΔΔΗΕ (HEDNO)", "domain": "deddie.gr", "sector": "Energy distribution",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Grid operator — depots + offices nationwide."},

    # ── Multinational BRANDS with a Greece presence ───────────────────────────
    {"name": "Mastercard (Greece)", "domain": "mastercard.com", "sector": "Payments / Fintech",
     "criteria": ["brand_name"], "note": "Regional office — prestige reference logo."},
    {"name": "Visa (Greece)", "domain": "visa.com", "sector": "Payments / Fintech",
     "criteria": ["brand_name"], "note": "Regional office."},
    {"name": "Microsoft Hellas", "domain": "microsoft.com", "sector": "Technology",
     "criteria": ["brand_name", "large_footprint"], "note": "Greek HQ + new Attica data-center region."},
    {"name": "Google Greece", "domain": "google.com", "sector": "Technology",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "Amazon (AWS Greece)", "domain": "amazon.com", "sector": "Technology / Cloud",
     "criteria": ["brand_name", "large_footprint"], "note": "Local zone / office."},
    {"name": "IBM Hellas", "domain": "ibm.com", "sector": "Technology",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "SAP Hellas", "domain": "sap.com", "sector": "Enterprise software",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "Cisco Greece", "domain": "cisco.com", "sector": "Networking",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "Pfizer Hellas", "domain": "pfizer.com", "sector": "Pharma",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + Thessaloniki Digital Hub; high-compliance."},
    {"name": "Novartis Hellas", "domain": "novartis.com", "sector": "Pharma",
     "criteria": ["brand_name", "large_footprint"], "note": "Pharma offices — high-hygiene/compliance fit."},
    {"name": "Roche Hellas", "domain": "roche.com", "sector": "Pharma",
     "criteria": ["brand_name"], "note": "Pharma offices."},
    {"name": "GlaxoSmithKline Hellas", "domain": "gsk.com", "sector": "Pharma",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + possible production."},
    {"name": "Procter & Gamble Hellas", "domain": "pg.com", "sector": "Consumer goods",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + plant/distribution."},
    {"name": "Unilever Hellas", "domain": "unilever.com", "sector": "Consumer goods",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + supply sites."},
    {"name": "Nestlé Hellas", "domain": "nestle.gr", "sector": "Food / Beverages",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + factories."},
    {"name": "PepsiCo Hellas (Tasty)", "domain": "pepsico.com", "sector": "Food / Beverages",
     "criteria": ["brand_name", "large_footprint"], "note": "Snack/beverage plants."},
    {"name": "Vodafone Greece", "domain": "vodafone.gr", "sector": "Telecom",
     "criteria": ["brand_name", "large_footprint"], "note": "HQ + stores + network sites."},
    {"name": "Nova (Wind Hellas)", "domain": "nova.gr", "sector": "Telecom",
     "criteria": ["brand_name", "large_footprint"], "note": "HQ + stores."},
    {"name": "Siemens Hellas", "domain": "siemens.com", "sector": "Industry / Tech",
     "criteria": ["brand_name", "large_footprint"], "note": "Offices + project sites."},
    {"name": "Schneider Electric Hellas", "domain": "se.com", "sector": "Industry / Energy",
     "criteria": ["brand_name"], "note": "Office + warehouse."},
    {"name": "Philips Hellas", "domain": "philips.gr", "sector": "Healthcare tech",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "Samsung Greece", "domain": "samsung.com", "sector": "Electronics",
     "criteria": ["brand_name"], "note": "Office presence."},
    {"name": "Deloitte Greece", "domain": "deloitte.com", "sector": "Professional services",
     "criteria": ["brand_name", "large_footprint"], "note": "Large office HQ — direct peer of EY client."},
    {"name": "PwC Greece", "domain": "pwc.com", "sector": "Professional services",
     "criteria": ["brand_name", "large_footprint"], "note": "Large office HQ."},
    {"name": "KPMG Greece", "domain": "kpmg.com", "sector": "Professional services",
     "criteria": ["brand_name", "large_footprint"], "note": "Large office HQ."},
    {"name": "Accenture Greece", "domain": "accenture.com", "sector": "Consulting / Tech",
     "criteria": ["brand_name", "large_footprint"], "note": "Growing delivery center / offices."},
    {"name": "IKEA Greece (Fourlis)", "domain": "ikea.gr", "sector": "Retail / Furniture",
     "criteria": ["brand_name", "large_footprint"], "note": "Huge big-box stores + warehouses."},
    {"name": "Leroy Merlin Greece", "domain": "leroymerlin.gr", "sector": "Retail / DIY",
     "criteria": ["brand_name", "large_footprint"], "note": "Very large-format stores."},
    {"name": "Decathlon Greece", "domain": "decathlon.gr", "sector": "Retail / Sports",
     "criteria": ["brand_name", "large_footprint"], "note": "Large-format stores."},
    {"name": "H&M Hellas", "domain": "hm.com", "sector": "Retail / Fashion",
     "criteria": ["brand_name", "large_footprint"], "note": "Mall + high-street store network."},
    {"name": "Inditex Greece (Zara)", "domain": "zara.com", "sector": "Retail / Fashion",
     "criteria": ["brand_name", "large_footprint"], "note": "Large flagship + mall stores."},
    {"name": "Nike (Greece)", "domain": "nike.com", "sector": "Retail / Sports",
     "criteria": ["brand_name"], "note": "Brand stores."},
    {"name": "adidas Greece", "domain": "adidas.gr", "sector": "Retail / Sports",
     "criteria": ["brand_name"], "note": "Brand stores."},
    {"name": "McDonald's Greece", "domain": "mcdonalds.gr", "sector": "Food service",
     "criteria": ["brand_name", "large_footprint"], "note": "Restaurant network — hygiene-critical."},
    {"name": "L'Oréal Hellas", "domain": "loreal.com", "sector": "Cosmetics",
     "criteria": ["brand_name"], "note": "Offices + distribution."},
    {"name": "DHL Hellas", "domain": "dhl.com", "sector": "Logistics",
     "criteria": ["brand_name", "large_footprint"], "note": "Sorting hubs + warehouses."},
    {"name": "DSV Greece", "domain": "dsv.com", "sector": "Logistics",
     "criteria": ["brand_name", "large_footprint"], "note": "Large logistics warehouses."},
    {"name": "Maersk Greece", "domain": "maersk.com", "sector": "Shipping / Logistics",
     "criteria": ["brand_name", "large_footprint"], "note": "Port/logistics operations + offices."},

    # ── Large-footprint Greek sites: malls, hospitals, hotels, data centers ───
    {"name": "Hygeia Hospital (Hellenic Healthcare Group)", "domain": "hygeia.gr", "sector": "Healthcare",
     "criteria": ["large_footprint"], "note": "Large private hospital — high-hygiene; ALTER EGO's core specialty."},
    {"name": "Metropolitan Hospital (HHG)", "domain": "metropolitan-hospital.gr", "sector": "Healthcare",
     "criteria": ["large_footprint"], "note": "Large private hospital — hygiene-critical."},
    {"name": "Henry Dunant Hospital", "domain": "dunant.gr", "sector": "Healthcare",
     "criteria": ["large_footprint"], "note": "Large hospital campus."},
    {"name": "Euromedica", "domain": "euromedica.gr", "sector": "Healthcare",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Hospital/clinic network nationwide."},
    {"name": "Errikos Dynan Hospital", "domain": "errikosdynan.gr", "sector": "Healthcare",
     "criteria": ["large_footprint"], "note": "Large private hospital."},
    {"name": "The Mall Athens (Lamda)", "domain": "themallathens.gr", "sector": "Retail / Mall",
     "criteria": ["large_footprint"], "note": "Major shopping mall — huge footfall + common areas."},
    {"name": "Golden Hall (Lamda)", "domain": "goldenhall.gr", "sector": "Retail / Mall",
     "criteria": ["large_footprint"], "note": "Premium mall — large common-area + security needs."},
    {"name": "Mediterranean Cosmos (Lamda)", "domain": "mediterraneancosmos.gr", "sector": "Retail / Mall",
     "criteria": ["large_footprint"], "note": "Thessaloniki's largest mall."},
    {"name": "McArthurGlen Designer Outlet Athens", "domain": "mcarthurglen.com", "sector": "Retail / Outlet",
     "criteria": ["brand_name", "large_footprint"], "note": "Large outlet village."},
    {"name": "Smart Park", "domain": "smartpark.gr", "sector": "Retail / Mall",
     "criteria": ["large_footprint"], "note": "Open-air retail park, Spata."},
    {"name": "River West / Westpolis", "domain": "riverwest.gr", "sector": "Retail / Mall",
     "criteria": ["large_footprint"], "note": "Large retail complex, Egaleo."},
    {"name": "Costa Navarino", "domain": "costanavarino.com", "sector": "Hospitality",
     "criteria": ["brand_name", "large_footprint"], "note": "Vast luxury resort estate — housekeeping + grounds."},
    {"name": "Grand Hyatt Athens", "domain": "hyatt.com", "sector": "Hospitality",
     "criteria": ["brand_name", "large_footprint"], "note": "Large city hotel."},
    {"name": "Hilton Athens (Conrad)", "domain": "hilton.com", "sector": "Hospitality",
     "criteria": ["brand_name", "large_footprint"], "note": "Major flagship hotel."},
    {"name": "Wyndham / Electra Hotels", "domain": "electrahotels.gr", "sector": "Hospitality",
     "criteria": ["large_footprint"], "note": "Hotel group — housekeeping/IFM."},
    {"name": "Sani/Ikos Group", "domain": "saniikos.com", "sector": "Hospitality",
     "criteria": ["large_greek_company", "large_footprint"], "note": "Large luxury resort group."},
    {"name": "Digital Realty Athens", "domain": "digitalrealty.com", "sector": "Data centers",
     "criteria": ["brand_name", "large_footprint"], "note": "Data-center facility — uptime + security critical."},
    {"name": "Lamda Hellix (Data Centers)", "domain": "lamdahellix.com", "sector": "Data centers",
     "criteria": ["large_footprint"], "note": "Greek data-center operator — high-security, 24/7."},
    {"name": "National & Kapodistrian University of Athens", "domain": "uoa.gr", "sector": "Education",
     "criteria": ["large_footprint"], "note": "Large multi-building campus, high footfall."},
    {"name": "Aristotle University of Thessaloniki", "domain": "auth.gr", "sector": "Education",
     "criteria": ["large_footprint"], "note": "Largest Greek university campus."},
    {"name": "Stavros Niarchos Park / SNF (estate ops)", "domain": "snf.org", "sector": "Public / Cultural",
     "criteria": ["large_footprint"], "note": "Note: SNFCC is an existing ALTER EGO reference — target adjacent venues only."},
    {"name": "OAKA Olympic Stadium Complex", "domain": "oaka.com.gr", "sector": "Public / Sports venue",
     "criteria": ["large_footprint"], "note": "Huge stadium/sports complex, high footfall events."},
]


def domain_for_name(name: str) -> str | None:
    """Best-effort domain lookup for a company name (used to give news-sourced
    leads an email when they match a company we already know). Token-overlap match."""
    if not name:
        return None
    import re
    def toks(s):
        s = re.sub(r"\(.*?\)", "", s.lower())
        return {t for t in re.split(r"[^\wά-ώα-ω]+", s) if len(t) > 2}
    target = toks(name)
    if not target:
        return None
    for c in SEED_COMPANIES:
        if target & toks(c["name"]):
            return c.get("domain")
    return None
